$base = "D:\自建\项目\app\Backend\ClipBoard"
dir "$base\01-Domain\ClipBoard.Domain.csproj"
dir "$base\02-Shared\ClipBoard.Shared.csproj"
dir "$base\local-packages\*.nupkg"
Write-Host "=== Domain csproj ==="
Get-Content "$base\01-Domain\ClipBoard.Domain.csproj"
Write-Host "=== Shared csproj ==="
Get-Content "$base\02-Shared\ClipBoard.Shared.csproj"
Write-Host "=== nuget.config ==="
Get-Content "$base\nuget.config"